# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Get paper daily

on:
  workflow_dispatch:
  schedule:
  - cron: "0 3 * * *"

env:
  GITHUB_USER_NAME: DukeEnglish
  GITHUB_USER_EMAIL: ljyduke@gmail.com
  
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: get paper
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Python Env
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          #architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # pip install arxiv
          # pip install requests
          
      - name: Run daily arxiv 
        run: |
          export PYTHONPATH=.
          python crontab/paper_update.py --BAIDU_API_KEY=${{ secrets.BD_API_KEY }} --BAIDU_SECRET_KEY=${{ secrets.BD_SECRET_KEY }}
          
      - name: Push new index.md
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Github Action Automatic Get New Paper"
          files: docs/ data/
          rebase: 'true'
          name: ${{ env.GITHUB_USER_NAME }}
          email: ${{ env.GITHUB_USER_EMAIL }}
